// <auto-generated />
using System;
using EFCore_ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_ORM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241105110532_initialDbCreation")]
    partial class initialDbCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore_ORM.Models.Department", b =>
                {
                    b.Property<int>("Dnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dnumber"));

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mgr_SSN")
                        .HasColumnType("int");

                    b.Property<DateTime>("Mgr_StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Dnumber");

                    b.HasIndex("Mgr_SSN");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Dependent", b =>
                {
                    b.Property<int>("ESSN")
                        .HasColumnType("int");

                    b.Property<string>("DependentName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Bdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ESSN", "DependentName");

                    b.ToTable("dependents");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Dept_Locations", b =>
                {
                    b.Property<int>("Dnumber")
                        .HasColumnType("int");

                    b.Property<string>("Dlocation")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Dnumber", "Dlocation");

                    b.ToTable("Dept_Locations");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Employee", b =>
                {
                    b.Property<int>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SSN"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Bdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dno")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MidName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<int>("Super_SSN")
                        .HasColumnType("int");

                    b.HasKey("SSN");

                    b.HasIndex("Dno");

                    b.HasIndex("Super_SSN");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Project", b =>
                {
                    b.Property<int>("Pnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pnumber"));

                    b.Property<int>("Dnum")
                        .HasColumnType("int");

                    b.Property<string>("Plocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pnumber");

                    b.HasIndex("Dnum");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Works_On", b =>
                {
                    b.Property<int>("ESSN")
                        .HasColumnType("int");

                    b.Property<int>("Pno")
                        .HasColumnType("int");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ESSN", "Pno");

                    b.HasIndex("Pno");

                    b.ToTable("Works_On");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Department", b =>
                {
                    b.HasOne("EFCore_ORM.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("Mgr_SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Dependent", b =>
                {
                    b.HasOne("EFCore_ORM.Models.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("ESSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Dept_Locations", b =>
                {
                    b.HasOne("EFCore_ORM.Models.Department", "Department")
                        .WithMany("Dept_Locations")
                        .HasForeignKey("Dnumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Employee", b =>
                {
                    b.HasOne("EFCore_ORM.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("Dno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore_ORM.Models.Employee", "Supervisor")
                        .WithMany("Supervisees")
                        .HasForeignKey("Super_SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Project", b =>
                {
                    b.HasOne("EFCore_ORM.Models.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("Dnum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Works_On", b =>
                {
                    b.HasOne("EFCore_ORM.Models.Employee", "Employee")
                        .WithMany("Works_OnProj")
                        .HasForeignKey("ESSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore_ORM.Models.Project", "Project")
                        .WithMany("Works_OnEmps")
                        .HasForeignKey("Pno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Department", b =>
                {
                    b.Navigation("Dept_Locations");

                    b.Navigation("Employees");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Employee", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("Supervisees");

                    b.Navigation("Works_OnProj");
                });

            modelBuilder.Entity("EFCore_ORM.Models.Project", b =>
                {
                    b.Navigation("Works_OnEmps");
                });
#pragma warning restore 612, 618
        }
    }
}
